### PR TITLE
Add Auradin Build

### PR DESCRIPTION
**Pull request by theBGuy**

### CODE REVIEW

**Comment by theBGuy** [comment]
oh when shall I be merged [https://medi
giphy

**Comment by theBGuy** [comment]
yawn

**Comment by theBGuy** [comment]
Note: With the changes I made in the currently closed respec PR, doing a check for finalBuild specific things would be much easier

**Comment by theBGuy** [comment]
Over a month...

**Comment by isid0re** [comment]
I appreciate the enthusiasm, but I will get to things when I get to them.

**Pull request closed without merging**
