### PR TITLE
Code improvement.

### PR DESCRIPTION
**Pull request by jonasmello**
Added a mapper to make it easier to read code and make it easier to modify as needed.

### CODE REVIEW

**Comment by isid0re** [comment]
A mapper is a good idea. Thanks for bringing this up. 

Looking thru the code submission, I saw a few errors in the changes (mostlikely from a find/replace all).  

Also, you have me wondering if a prototype function would be better/cleaner. What are your thoughts?

**Comment by jonasmello** [comment]
Sorry for the mistakes.
I also noticed that line 486 is outside the scope of the variable.
I think the best alternative would be to create an object inside Check. Ex .: Check.questIdMap.baal
The goal is to have intellisense, a function with a string parameter will not provide this.
Can I write?

**Comment by jonasmello** [comment]
Well, I'll commit the code here and wait for your feedback.

**Comment by isid0re** [comment]
Please do. Work and family keeps me pretty busy so I'm not always checking the repo. But i do try and check it once a day atleast.

**Comment by jonasmello** [comment]
Is already done. I'm even using it on my machine and it's working perfectly.
If the code is to your liking, you can merge it.

**Comment by isid0re** [comment]
thank you Jonas, 

I'm looking it over and comparing to the existing Quest.Status() function in Quest.js. I've got some food for thought as I'd like to avoid repetitive code. Again thanks for submitting the PR.

**Comment by jonasmello** [comment]
After you spoke I went to look at Quest.js and the Status function does everything we need. It is not really necessary to create this mapper.
I just don't understand why it is not being used in Globals.js.

**Comment by isid0re** [comment]
Globals.js was written long before quest.js and looks like it was lost in the shuffle. But thanks again for bringing this to my attention. I hadn't considered it prior.

**Pull request closed without merging**
